config/routes.rb
Rails.application.routes.draw do
	  get 'welcome/index'
  
  resources :messages
 
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def index
    @messages = Message.all
  end
	def show
    @message = Message.find(params[:id])
  end
	def new
		@message = Message.new
  end
  def edit
  @message = Message.find(params[:id])
end
  def create
  @message = Message.new(message_params)
 
  if @message.save
    redirect_to @message
  else
    render 'new'
  end
end
def update
  @message = Message.find(params[:id])
 
  if @message.update(message_params)
    redirect_to @message
  else
    render 'edit'
  end
end
def destroy
  @message = Message.find(params[:id])
  @message.destroy
 
  redirect_to messages_path
end
 
private
  def message_params
    params.require(:message).permit(:title, :text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstProjectRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
 
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@message.errors.count, "error") %> prohibited
        this message from being saved:
      </h2>
      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/messages/edit.html.erb
<h1>Edit message</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<%= link_to 'New message', new_message_path %>
<h1>Listing messages</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @messages.each do |message| %>
    <tr>
      <td><%= message.title %></td>
      <td><%= message.text %></td>
      <td><%= link_to 'Show', message_path(message) %></td>
      <td><%= link_to 'Edit', edit_message_path(message) %></td>
      <td><%= link_to 'Destroy', message_path(message),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/messages/new.html.erb
<h1>New message</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>
<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/welcome/edit.html.erb
<h1>Editing message</h1>
 
<%= form_for :message, url: message_path(@message), method: :patch do |f| %>
 
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@message.errors.count, "error") %> prohibited
        this message from being saved:
      </h2>
      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', messages_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'messages' %>